/**
 * The evidence behind provisional scores (METHODOLOGY.md, section 3): for every
 * pair of versions of the same line, measured by Artificial Analysis, where the
 * newer one has an Intelligence Index at least that of the older, did the newer
 * one score at least as well on the Coding Index?
 *
 * Reads the cached Artificial Analysis download and writes
 * docs/successor-backtest.md. Run: npx tsx tools/successor-backtest.ts
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { lineOf } from '../src/engine/lineage.js';
import type { AaModel } from '../src/sources/artificialanalysis.js';

const root = fileURLToPath(new URL('..', import.meta.url));
const download = JSON.parse(readFileSync(`${root}data/cache/artificialanalysis-models.json`, 'utf8')) as { fetchedAt: string; models: AaModel[] };

// Effort variants are one model: keep the best-scoring variant of each.
const VARIANT = /-(max|xhigh|high|medium|low|minimal|non-reasoning|reasoning|thinking|adaptive)$/;
type Row = { key: string; name: string; released: string; coding: number; intelligence: number };
const best = new Map<string, Row>();
for (const m of download.models) {
  const coding = m.evaluations?.artificial_analysis_coding_index;
  const intelligence = m.evaluations?.artificial_analysis_intelligence_index;
  if (typeof coding !== 'number' || typeof intelligence !== 'number' || !m.release_date) continue;
  let slug = m.slug;
  while (VARIANT.test(slug)) slug = slug.replace(VARIANT, '');
  const key = `${m.model_creator?.id ?? 'unknown'}/${slug}`;
  const prev = best.get(key);
  if (!prev || coding > prev.coding) best.set(key, { key, name: m.name, released: m.release_date, coding, intelligence });
}

const after = (a: number[], b: number[]) => {
  for (let i = 0; i < Math.max(a.length, b.length); i++) if ((a[i] ?? 0) !== (b[i] ?? 0)) return (a[i] ?? 0) > (b[i] ?? 0);
  return false;
};

const pairs: { older: Row; newer: Row }[] = [];
const rows = [...best.values()];
for (const older of rows) {
  const lo = lineOf(older.key);
  if (!lo) continue;
  for (const newer of rows) {
    const ln = lineOf(newer.key);
    if (newer === older || !ln || ln.line !== lo.line) continue;
    if (!after(ln.version, lo.version) || newer.released <= older.released) continue;
    if (newer.intelligence < older.intelligence) continue;
    pairs.push({ older, newer });
  }
}
pairs.sort((a, b) => a.newer.coding - a.older.coding - (b.newer.coding - b.older.coding));

const held = pairs.filter((p) => p.newer.coding >= p.older.coding).length;
const diffs = pairs.map((p) => p.newer.coding - p.older.coding).sort((a, b) => a - b);
const median = diffs.length ? diffs[Math.floor(diffs.length / 2)]! : 0;
const f = (v: number) => v.toFixed(1);

const md = `# Successor backtest

Evidence for the provisional scores described in [METHODOLOGY.md](../METHODOLOGY.md), section 3.
Generated by \`tools/successor-backtest.ts\` from the Artificial Analysis download of ${download.fetchedAt.slice(0, 10)}.

Pairs of versions of the same line, both measured, where the newer version's Intelligence Index is at least the older one's: **${pairs.length} pairs**. The newer version scored at least as well on the Coding Index in **${held}** of them. Median change: **${median >= 0 ? '+' : ''}${f(median)} points**.

This is a record of the past, not a probability for the next release.

| Older version | Newer version | Intelligence (old → new) | Coding (old → new) | Change |
|---|---|---|---|---|
${pairs.map((p) => `| ${p.older.name} | ${p.newer.name} | ${f(p.older.intelligence)} → ${f(p.newer.intelligence)} | ${f(p.older.coding)} → ${f(p.newer.coding)} | ${p.newer.coding - p.older.coding >= 0 ? '+' : ''}${f(p.newer.coding - p.older.coding)} |`).join('\n')}
`;
mkdirSync(`${root}docs`, { recursive: true });
writeFileSync(`${root}docs/successor-backtest.md`, md);
console.log(`${pairs.length} pairs, ${held} held, median ${f(median)}`);
